In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
list1=[10,20,30,40,5]
print(f"List :",list1)

#Now print array from list
arr_list = np.array(list1)
print("Created array from above List :",arr_list)

List : [10, 20, 30, 40, 5]
Created array from above List : [10 20 30 40  5]


In [ ]:
# 1. Creating numpy arrays
arr1 = np.array([1, 2, 3, 4, 5])        # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
arr3 = np.zeros((2, 3))                 # 2x3 array of zeros
arr4 = np.ones((3, 2))                  # 3x2 array of ones
arr5 = np.eye(3)                        # Identity matrix (3x3)
arr5_1 = np.identity(3)                 # Identity matrix method 2 (3x3)
arr6 = np.arange(0, 10, 2)              # Array from 0 to 8 with step 2
arr7 = np.linspace(0, 1, 5)             # 5 numbers between 0 and 1
arr8 = np.empty((3,2))                  # Creates an array without initializing its values, Possible Output (values may vary)

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Zeros:\n", arr3)
print("Ones:\n", arr4)
print("Identity Matrix:\n", arr5)
print("Identity Matrix Method2:\n", arr5_1)
print("Arange:", arr6)
print("Linspace:", arr7)
print("Empty:\n",arr8)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix Method2:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Empty:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 2. Array attributes
print("\nArray shape:", arr2.shape)   # rows, columns
print("Array dimensions:", arr2.ndim) # number of dimensions
print("Array size:", arr2.size)       # total elements
print("Array datatype:", arr2.dtype)  # data type of elements



# 2.1. Specify datatype while creating array
arr1d = np.array([1, 2, 3, 4], dtype=np.float32)   # explicitly set float type
arr2d = np.array([1, 2, 3, 4], dtype=np.int64)     # explicitly set integer type
arr3d = np.array([1.5, 2.8, 3.9], dtype=np.int32)  # float values stored as integers

print("\narr1d (float32):", arr1d, "dtype:", arr1d.dtype)
print("arr2d (int64):", arr2d, "dtype:", arr2d.dtype)
print("arr3d (int32, truncated):", arr3d, "dtype:", arr3d.dtype)


# 2.2. Change datatype of an existing array
arr4d = np.array([10, 20, 30, 40])  # default int64
print("\nOriginal arr4:", arr4d, "dtype:", arr4d.dtype)

# Convert int → float
arr4_float = arr4d.astype(np.float64)
print("arr4d converted to float:", arr4_float, "dtype:", arr4_float.dtype)

# Convert int → string
arr4_str = arr4d.astype(str)
print("arr4d converted to string:", arr4_str, "dtype:", arr4_str.dtype)

# Convert float → int
arr5d = np.array([3.7, 8.9, 2.2])
arr5d_int = arr5d.astype(int)   # decimals are truncated (not rounded!)
print("\nOriginal arr5:", arr5d, "dtype:", arr5d.dtype)
print("arr5 converted to int:", arr5d_int, "dtype:", arr5d_int.dtype)



Array shape: (2, 3)
Array dimensions: 2
Array size: 6
Array datatype: int64

arr1d (float32): [1. 2. 3. 4.] dtype: float32
arr2d (int64): [1 2 3 4] dtype: int64
arr3d (int32, truncated): [1 2 3] dtype: int32

Original arr4: [10 20 30 40] dtype: int64
arr4d converted to float: [10. 20. 30. 40.] dtype: float64
arr4d converted to string: ['10' '20' '30' '40'] dtype: <U21

Original arr5: [3.7 8.9 2.2] dtype: float64
arr5 converted to int: [3 8 2] dtype: int64


In [ ]:
# 3. Indexing and slicing
print("\nFirst element of arr1:", arr1[0])
print("Last element of arr1:", arr1[-1])
print("First row of arr2:", arr2[0])
print("Second column of arr2:", arr2[:, 1])  # all rows, 2nd column


First element of arr1: 1
Last element of arr1: 5
First row of arr2: [1 2 3]
Second column of arr2: [2 5]


In [ ]:
# 4. Array operations
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square of a:", a ** 2)
print("Square root of a:", np.sqrt(a))



Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Square of a: [ 100  400  900 1600]
Square root of a: [3.16227766 4.47213595 5.47722558 6.32455532]


In [ ]:
# 5. Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("\nMatrix addition:\n", m1 + m2)

print("Matrix multiplication:\n", m1 * m2)   # or np.dot(m1, m2)

print("Transpose of Matrix m1:\n", m1.T)



Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[ 5 12]
 [21 32]]
Transpose of Matrix m1:
 [[1 3]
 [2 4]]


In [ ]:
# 6. Useful functions
rand_arr = np.random.rand(2, 3)  # Random numbers between 0 and 1
print("\nRandom Array:\n", rand_arr)

print("Max value:", rand_arr.max())
print("Min value:", rand_arr.min())
print("Sum of elements:", rand_arr.sum())
print("Mean:", rand_arr.mean())
print("Standard Deviation:", rand_arr.std())

# 7. Reshaping arrays
reshaped = np.arange(12).reshape(3, 4)
print("\nReshaped Array (3x4):\n", reshaped)


Random Array:
 [[0.39463064 0.30152656 0.55447576]
 [0.98156102 0.09113633 0.12370663]]
Max value: 0.9815610173989205
Min value: 0.09113633114130659
Sum of elements: 2.4470369296167482
Mean: 0.40783948826945804
Standard Deviation: 0.3008786773238733

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 8. A scalar is just a single value

arr_scalar = np.array([2, 4, 6, 8])

# Scalar operations apply to every element
print("Multiply array by scalar:", arr_scalar * 3)
print("Add scalar to array:", arr_scalar + 5)
print("Divide array by scalar:", arr_scalar / 2)

Multiply array by scalar: [ 6 12 18 24]
Add scalar to array: [ 7  9 11 13]
Divide array by scalar: [1. 2. 3. 4.]


In [ ]:
# 9. Broadcasting allows arrays of different shapes to be combined
arrs = np.array([1, 2, 3, 4])

# A scalar (single number) is broadcasted across the array
print("Add scalar 10 to array:", arrs + 10)

# Broadcasting with a smaller array
matrix = np.array([[1], [2], [3]])  # Shape (3,1)
vector = np.array([10, 20, 30])     # Shape (3,)
result = matrix + vector            # vector is broadcasted to match matrix shape

print("Matrix:\n", matrix)
print("Vector:", vector)
print("Broadcasted Addition:\n", result)

Add scalar 10 to array: [11 12 13 14]
Matrix:
 [[1]
 [2]
 [3]]
Vector: [10 20 30]
Broadcasted Addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 10. Filter concepts
arr = np.array([5, 10, 15, 20, 25, 30])

# Condition to filter values greater than 15
condition = arr > 15

print("Boolean mask:", condition)  # Shows True/False
print("Filtered values:", arr[condition])  # Only values > 15

# Multiple conditions using logical operators
print("Values between 10 and 25:", arr[(arr > 10) & (arr < 25)])

# Filter even numbers
print("Even numbers:", arr[arr % 2 == 0])

Boolean mask: [False False False  True  True  True]
Filtered values: [20 25 30]
Values between 10 and 25: [15 20]
Even numbers: [10 20 30]
